id: IF6DC3CE2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T15:34:00+00:00'
last_modified: '2022-06-15T15:26:57.057613+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4285
  title: བློ་སྦྱོང་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2C3B:
      image_group_id: I1PD100489
      title: Volume 1 of blo sbyong brgya rtsa
      total_pages: 548
      order: 1
      base_file: 2C3B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
