id: IF6DC3CE2
legacy_id: P000315
ocr_import_info:
  bdrc_scan_id: W1KG4285
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T15:32:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:31:58.018625+00:00'
last_modified: 2022-08-31 23:32:08.974265
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4285
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4285
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་སྦྱོང་སྐོར་ཕྱོགས་བསྒྲིགས།
statistics: null
quality: null
bases:
  I1PD100490:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100490
      total_pages: 466
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD100490.txt
    legacy_id: v002
  I1PD100489:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100489
      total_pages: 548
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD100489.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
